/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien;

import Helper.ChiaSeDuLieu;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    private QuanLi_NV_Panel NhanVien_Panel;
    private QuanLi_Luong_Panel Luong_Panel;

    /**
     * Creates new form GiaoDienQuanLi
     */
    public GiaoDienChinh() {

          initComponents();
        setLocationRelativeTo(null);
           
        setExtendedState(getExtendedState() |  JFrame.MAXIMIZED_BOTH); //Kích thước giao diện   
//          GiaoDienDangNhap frame = new GiaoDienDangNhap(this, true);
//           frame.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        GDQL_DangXuat = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        GDQL_NhanVien = new javax.swing.JButton();
        GDQL_Luong = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        GDQL_GioiThieu = new javax.swing.JButton();
        BangChinh_Tab = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHeThong = new javax.swing.JMenu();
        MenuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuThoat = new javax.swing.JMenuItem();
        QuanLi = new javax.swing.JMenu();
        MenuQuanLi_NV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuQuanLi_Luong = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        GDQL_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/arrow32.png"))); // NOI18N
        GDQL_DangXuat.setText("Đăng Xuất");
        GDQL_DangXuat.setFocusable(false);
        GDQL_DangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GDQL_DangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GDQL_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDQL_DangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(GDQL_DangXuat);
        jToolBar1.add(jSeparator4);

        GDQL_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bussiness-man32.png"))); // NOI18N
        GDQL_NhanVien.setText("Quản Lý Nhân Viên");
        GDQL_NhanVien.setFocusable(false);
        GDQL_NhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GDQL_NhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GDQL_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDQL_NhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(GDQL_NhanVien);

        GDQL_Luong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/payment-method32.png"))); // NOI18N
        GDQL_Luong.setText("Quản Lý Lương");
        GDQL_Luong.setFocusable(false);
        GDQL_Luong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GDQL_Luong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GDQL_Luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDQL_LuongActionPerformed(evt);
            }
        });
        jToolBar1.add(GDQL_Luong);
        jToolBar1.add(jSeparator6);

        GDQL_GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-32.png"))); // NOI18N
        GDQL_GioiThieu.setText("Giới Thiệu");
        GDQL_GioiThieu.setFocusable(false);
        GDQL_GioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GDQL_GioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GDQL_GioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDQL_GioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(GDQL_GioiThieu);

        MenuHeThong.setText("Hệ thống");

        MenuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/arrow16.png"))); // NOI18N
        MenuDangXuat.setText("Đăng Xuất");
        MenuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDangXuatActionPerformed(evt);
            }
        });
        MenuHeThong.add(MenuDangXuat);
        MenuHeThong.add(jSeparator1);

        MenuThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        MenuThoat.setText("Thoát");
        MenuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuThoatActionPerformed(evt);
            }
        });
        MenuHeThong.add(MenuThoat);

        jMenuBar1.add(MenuHeThong);

        QuanLi.setText("Quản lý");

        MenuQuanLi_NV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuQuanLi_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bussiness-man16.png"))); // NOI18N
        MenuQuanLi_NV.setText("Quản Lý Nhân Viên");
        MenuQuanLi_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuanLi_NVActionPerformed(evt);
            }
        });
        QuanLi.add(MenuQuanLi_NV);
        QuanLi.add(jSeparator2);

        MenuQuanLi_Luong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuQuanLi_Luong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/payment-method16.png"))); // NOI18N
        MenuQuanLi_Luong.setText("Quản Lý Lương");
        MenuQuanLi_Luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuanLi_LuongActionPerformed(evt);
            }
        });
        QuanLi.add(MenuQuanLi_Luong);

        jMenuBar1.add(QuanLi);

        jMenu3.setText("Trợ giúp");
        jMenu3.add(jSeparator3);

        MenuGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon-16.png"))); // NOI18N
        MenuGioiThieu.setText("Giới Thiệu");
        MenuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(MenuGioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BangChinh_Tab, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BangChinh_Tab, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuThoatActionPerformed

    private void MenuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDangXuatActionPerformed
        GDQL_DangXuatActionPerformed(evt);
    }//GEN-LAST:event_MenuDangXuatActionPerformed

    private void MenuQuanLi_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuanLi_NVActionPerformed
    if(NhanVien_Panel==null){
                NhanVien_Panel = new QuanLi_NV_Panel();
                ImageIcon icon = new ImageIcon(getClass().getResource(  "/icon/bussiness-man16.png"));
                BangChinh_Tab.addTab("Quản Lý Nhân Viên", icon, NhanVien_Panel,"Quản Lý Nhân Viên");
        }
        BangChinh_Tab.setSelectedComponent(NhanVien_Panel);        
    
    }//GEN-LAST:event_MenuQuanLi_NVActionPerformed

    private void MenuQuanLi_LuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuanLi_LuongActionPerformed
         if(Luong_Panel==null){
                Luong_Panel = new QuanLi_Luong_Panel();
                ImageIcon icon = new ImageIcon(getClass().getResource(  "/icon/payment-method16.png"));
                BangChinh_Tab.addTab("Quản Lý Lương", icon, Luong_Panel,"Quản Lý Lương");
        }
        BangChinh_Tab.setSelectedComponent(Luong_Panel);
                                            
    }//GEN-LAST:event_MenuQuanLi_LuongActionPerformed

    private void GDQL_GioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDQL_GioiThieuActionPerformed
        GioiThieu gioithieu = new GioiThieu(this, true);
        
        gioithieu.setVisible(true);
    }//GEN-LAST:event_GDQL_GioiThieuActionPerformed

    private void MenuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGioiThieuActionPerformed
           GDQL_GioiThieuActionPerformed(evt) ;                                          

    }//GEN-LAST:event_MenuGioiThieuActionPerformed

    private void GDQL_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDQL_DangXuatActionPerformed
        this.dispose(); // Đóng form giao diện chính
        //GiaoDienChinh DangXuat = new GiaoDienChinh();
       GiaoDienDangNhap DangXuat =  new GiaoDienDangNhap(this,true);       // Tạo đối tượng đăng nhập mới
       DangXuat.setVisible(true);        
         
    }//GEN-LAST:event_GDQL_DangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void GDQL_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDQL_NhanVienActionPerformed
        MenuQuanLi_NVActionPerformed(evt);
    }//GEN-LAST:event_GDQL_NhanVienActionPerformed

    private void GDQL_LuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDQL_LuongActionPerformed
        MenuQuanLi_LuongActionPerformed(evt);
    }//GEN-LAST:event_GDQL_LuongActionPerformed

// private void XuLyDangNhapThanhCong (){
//     lbl_GDQL_tenDangNhap.setText(ChiaSeDuLieu.nguoiDangNhap.getTenDangNhap());
//     lbl_GDQL_VaiTro.setText(ChiaSeDuLieu.nguoiDangNhap.getVaiTro());
//     
//      if  (ChiaSeDuLieu.nguoiDangNhap.getVaiTro().endsWith("Giảng Viên")){
//                MenuQuanLi_NV.setEnabled(false);
//                GDQL_NhanVien.setEnabled(false);
//                MenuQuanLi_Luong.setEnabled(true);
//                GDQL_Luong.setEnabled(true);
//                
//        }else if(ChiaSeDuLieu.nguoiDangNhap.getVaiTro().endsWith("Đào Tạo")){
//                MenuQuanLi_NV.setEnabled(true);
//                GDQL_NhanVien.setEnabled(true);
//                MenuQuanLi_Luong.setEnabled(false);
//                GDQL_Luong.setEnabled(false);
//        }
// }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
          
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {         
                  
               //new GiaoDienChinh().setVisible(true);
                  GiaoDienDangNhap dialog = new GiaoDienDangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
               }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BangChinh_Tab;
    private javax.swing.JButton GDQL_DangXuat;
    private javax.swing.JButton GDQL_GioiThieu;
    private javax.swing.JButton GDQL_Luong;
    private javax.swing.JButton GDQL_NhanVien;
    private javax.swing.JMenuItem MenuDangXuat;
    private javax.swing.JMenuItem MenuGioiThieu;
    private javax.swing.JMenu MenuHeThong;
    private javax.swing.JMenuItem MenuQuanLi_Luong;
    private javax.swing.JMenuItem MenuQuanLi_NV;
    private javax.swing.JMenuItem MenuThoat;
    private javax.swing.JMenu QuanLi;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
