/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Giao_Dien;

import Helper.HienThiThongBao;
import Helper.KTra_DuLieu;
import DAO.BangLuongDao;
import DAO.NhanVienDao;
import Model.BangLuong;
import Model.NhanVien;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class QuanLi_Luong_Panel extends javax.swing.JPanel {

    private GiaoDienChinh parentform;
     private DefaultTableModel tblModel;
private float  TongLuong, LuongCoBan;
  
    /**
     * Creates new form QuanLi_Diem_Panel
     */
    public QuanLi_Luong_Panel() {
        initComponents();
        
         TieuDeBang();
        
        TaiDuLieuVaoBang();
        /*
        Thêm tháng năm vào combobox
        */
        for(int i = 1; i < 13; i++){
           
            if(i>9){
                QLL_cbb_Thang.addItem(""+i);
            }else{
                 QLL_cbb_Thang.addItem("0"+i);
            }
        }
        for(int i = 2010; i < 2030 ; i++){
            QLL_cbb_Nam.addItem(""+i);
        }
    }
    
     /*
    Phương thức đặt tiêu đề vào bảng QLD_BangDiem
    */
    private void TieuDeBang(){
        
        tblModel = new DefaultTableModel();
      tblModel.setColumnIdentifiers(new String []{"Mã Nhân Viên","Họ Tên", "Tháng","Số Ngày Nghỉ", "Sô Giờ Làm Thêm", "Lương Cơ Bản",  "Tổng Lương"});

        QLL_table_BangLuong.setModel(tblModel);
    }

    /*
    Phương thức cho đọc dữ liệu CSDL hiển thị lên bảng
    */
    private  void TaiDuLieuVaoBang(){
        try {
         

                BangLuongDao dao = new BangLuongDao();
                List < BangLuong> list = dao.findTop(10);
                tblModel.setRowCount(0);
                for (BangLuong  it : list ){
                    tblModel.addRow(new Object[]{
                       it.getMaNhanVien(),it.getHoTenNV(), it.getThang(),it.getSoNgayNghi(),it.getSoGioLamThem(), it.getLuongCoBan(),it.getTinhLuong()});
                    tblModel.fireTableDataChanged();
                }
      
                 
                 
        } catch (Exception e) {
            e.printStackTrace();
            HienThiThongBao.ThongBaoLoi(parentform, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        QLL_txtTimKiem = new javax.swing.JTextField();
        QLL_btn_TimKiem = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        QLL_table_BangLuong = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        QLL_txtPhuCap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        QLL_cbb_Thang = new javax.swing.JComboBox<>();
        QLL_cbb_Nam = new javax.swing.JComboBox<>();
        QLL_btn_TinhLuong = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        QLL_lbl_TongLuong = new javax.swing.JLabel();
        QLL_btn_NhapMoi = new javax.swing.JButton();
        QLL_btn_Luu = new javax.swing.JButton();
        QLL_btn_CapNhat = new javax.swing.JButton();
        QLL_btn_Xoa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        QLL_txtMaNhanVien = new javax.swing.JTextField();
        QLL_txtHoTenNV = new javax.swing.JTextField();
        QLL_txtGioLamThem = new javax.swing.JTextField();
        QLL_txtSoNgayNghi = new javax.swing.JTextField();
        QLL_txtChucVu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        QLL_txtSDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Lương");

        jLabel2.setText("Mã Nhân Viên");

        QLL_btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon-16.png"))); // NOI18N
        QLL_btn_TimKiem.setText("Tìm Kiếm");
        QLL_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QLL_txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QLL_btn_TimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(QLL_txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLL_btn_TimKiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QLL_table_BangLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        QLL_table_BangLuong.setCellSelectionEnabled(true);
        QLL_table_BangLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLL_table_BangLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(QLL_table_BangLuong);

        jLabel10.setText("Tiền Phụ Cấp");

        QLL_txtPhuCap.setText("0");

        jLabel11.setText("Tháng Cần Tính");

        QLL_btn_TinhLuong.setText("Tính Lương");
        QLL_btn_TinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_TinhLuongActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Tổng Lương :");

        QLL_lbl_TongLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QLL_lbl_TongLuong.setText("0");

        QLL_btn_NhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset16.png"))); // NOI18N
        QLL_btn_NhapMoi.setText("Nhập Mới");
        QLL_btn_NhapMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                QLL_txtGioLamThemFocusLost(evt);
            }
        });
        QLL_btn_NhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_NhapMoiActionPerformed(evt);
            }
        });

        QLL_btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        QLL_btn_Luu.setText("Lưu");
        QLL_btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_LuuActionPerformed(evt);
            }
        });

        QLL_btn_CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        QLL_btn_CapNhat.setText("Cập Nhật");
        QLL_btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_CapNhatActionPerformed(evt);
            }
        });

        QLL_btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon-16.png"))); // NOI18N
        QLL_btn_Xoa.setText("Xóa");
        QLL_btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLL_btn_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QLL_lbl_TongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(QLL_cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QLL_cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QLL_btn_TinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(QLL_txtPhuCap)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(QLL_btn_NhapMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QLL_btn_Luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QLL_btn_CapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QLL_btn_Xoa))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(QLL_txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(QLL_cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QLL_cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(QLL_btn_TinhLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(QLL_lbl_TongLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLL_btn_NhapMoi)
                    .addComponent(QLL_btn_Luu)
                    .addComponent(QLL_btn_CapNhat)
                    .addComponent(QLL_btn_Xoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setText("Họ Tên");

        jLabel5.setText("Số Giờ Làm Thêm");

        jLabel6.setText("Chức Vụ");

        jLabel7.setText("Số Ngày Nghỉ");

        QLL_txtGioLamThem.setText("0");

        QLL_txtSoNgayNghi.setText("0");
        QLL_txtSoNgayNghi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                QLL_txtGioLamThemFocusLost(evt);
            }
        });

        jLabel8.setText("Số Điện Thoại");

        jLabel9.setText("Giờ");

        jLabel12.setText("Ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLL_txtHoTenNV)
                    .addComponent(QLL_txtMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QLL_txtChucVu)
                    .addComponent(QLL_txtSDT)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(QLL_txtSoNgayNghi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(QLL_txtGioLamThem, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(QLL_txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(QLL_txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLL_txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLL_txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLL_txtSoNgayNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(QLL_txtGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 245, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QLL_btn_NhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_NhapMoiActionPerformed
        QLL_txtMaNhanVien.setText("");
        QLL_txtChucVu.setText("");
        QLL_txtHoTenNV.setText("");
        QLL_txtSoNgayNghi.setText("");
        QLL_txtSDT.setText("");
        QLL_txtPhuCap.setText("0");
        QLL_txtGioLamThem.setText("");
        QLL_cbb_Thang.setSelectedIndex(0);
        QLL_cbb_Nam.setSelectedIndex(0);
        QLL_lbl_TongLuong.setText("0");
        
        
    }//GEN-LAST:event_QLL_btn_NhapMoiActionPerformed

    private void QLL_btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_LuuActionPerformed
             // Kiểm tra dữ liệu đã được nhập?
        StringBuilder sb = new StringBuilder();
            KTra_DuLieu.validateEmpty(QLL_txtMaNhanVien, sb, "Mã Nhân Viên Không Được Để Trống");           
            KTra_DuLieu.validateEmpty(QLL_txtGioLamThem, sb, " Vui Lòng Nhập Số Giờ Làm Thêm Của Nhân Viên");
             KTra_DuLieu.validateEmpty(QLL_txtSoNgayNghi, sb, " Vui Lòng Nhập Số Ngày Nghỉ Của Nhân Viên");
            
            if(sb.length()>0){
                HienThiThongBao.ThongBaoLoi (parentform, sb.toString(), "Lỗi");
                return;
            }
            
           try {
                      BangLuong BL=new BangLuong();
                      BL.setMaNhanVien(QLL_txtMaNhanVien.getText());
                      BL.setHoTenNV(QLL_txtHoTenNV.getText() );
                      BL.setSoNgayNghi(Integer.parseInt(QLL_txtSoNgayNghi.getText()));
                      BL.setSoGioLamThem(Integer.parseInt(QLL_txtGioLamThem.getText()));
                      BL.setLuongCoBan( LuongCoBan);
                      BL.setTinhLuong( TongLuong);
                      BL.setThang(QLL_cbb_Thang.getItemAt(QLL_cbb_Thang.getSelectedIndex()) + "/" + QLL_cbb_Nam.getItemAt(QLL_cbb_Nam.getSelectedIndex()));

                      BangLuongDao BLdao = new BangLuongDao();
                // Kiểm nhân viên đã có bảng lương chưa
                                 if  (BLdao.findByMaNhanVien( QLL_txtMaNhanVien.getText()) != null){
                                 // Hiển thị thông báo
                                            if(HienThiThongBao.ThongBaoXacNhan (parentform,"Bạn Có Muốn Cập Nhật Lương Không" , "Hỏi") == JOptionPane.NO_OPTION){
                                                         return;
                                             }
                                 //  Cập nhật bảng lương nhân viên vào csdl
                                            if(BLdao.update(BL)){
                                                      HienThiThongBao.ThongBao (parentform, "Lương Đã Được Cập Nhật ", "Thông Báo");
                                                      TaiDuLieuVaoBang();
                                            }else{
                                                         HienThiThongBao.ThongBaoXacNhan (parentform, "Lương Không Được Cập Nhật Do Lỗi", "Cảnh Báo");
                                            }
                                }else   {            
           // thêm bảng bảng lương nhân viên  vào csdl
                      if  (BLdao.insert(BL)){
                                 HienThiThongBao.ThongBao (parentform, "Lương Đã Được Lưu", "Thông Báo");
                                 TaiDuLieuVaoBang();
                      }else{
                                 HienThiThongBao.ThongBao (parentform, "Không Thể Lưu Vào Bảng Lương", "Thông Báo");
                                 }
                       }         
           } catch (Exception e) {          
                      e.printStackTrace();
                      HienThiThongBao.ThongBaoLoi (parentform, e.getMessage(), "Lỗi");
                      //   HienThiThongBao.ThongBaoXacNhan (parentform, "Nhân Viên Không Được Lưu Do Lỗi", "Cảnh Báo");
                            }
    }//GEN-LAST:event_QLL_btn_LuuActionPerformed

    private void QLL_btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_CapNhatActionPerformed
  
/*
        Kiểm tra dữ liệu đã được nhập?
        */     
        StringBuilder sb = new StringBuilder();
            KTra_DuLieu.validateEmpty(QLL_txtMaNhanVien, sb, "Mã Nhân Viên Không Được Để Trống");           
         
     
            
            if(sb.length()>0){
                HienThiThongBao.ThongBaoLoi (parentform, sb.toString(), "Lỗi");
                return;
            }
            
           try {
                        BangLuong BL=new BangLuong();
                        BL.setMaNhanVien(QLL_txtMaNhanVien.getText());
                        BL.setHoTenNV(QLL_txtHoTenNV.getText() );
                        BL.setSoNgayNghi(Integer.parseInt(QLL_txtSoNgayNghi.getText()));
                        BL.setSoGioLamThem(Integer.parseInt(QLL_txtGioLamThem.getText()));
                        BL.setLuongCoBan( LuongCoBan);
                        BL.setTinhLuong( TongLuong);
                        BL.setThang(QLL_cbb_Thang.getItemAt(QLL_cbb_Thang.getSelectedIndex()) + "/" + QLL_cbb_Nam.getItemAt(QLL_cbb_Nam.getSelectedIndex()));
                          BangLuongDao BLdao = new BangLuongDao();
           // Hiển thị thông báo
                           if(HienThiThongBao.ThongBaoXacNhan (parentform,"Bạn Có Muốn Cập Nhật Lương Không" , "Hỏi") == JOptionPane.NO_OPTION){
                           return;
                            }
                        if(BLdao.update(BL)){
                            HienThiThongBao.ThongBao (parentform, "Nhân Viên Đã Được Cập Nhật ", "Thông Báo");
                            TaiDuLieuVaoBang();
                          }else{
                                HienThiThongBao.ThongBaoXacNhan (parentform, "Nhân Viên Không Được Cập Nhật \nDo Không Có Nhân Viên Trong CSDL ", "Cảnh Báo");
                            }
                
                
           } catch (Exception e) {
                    e.printStackTrace();
                    HienThiThongBao.ThongBaoLoi (parentform, e.getMessage(), "Lỗi");
                 }
    }//GEN-LAST:event_QLL_btn_CapNhatActionPerformed

    private void QLL_txtGioLamThemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QLL_txtGioLamThemFocusLost
            if  ( QLL_txtGioLamThem.getText().equals("") ){
                return;
            }
            
            float luong=Float.parseFloat(QLL_txtGioLamThem.getText());
    }//GEN-LAST:event_QLL_txtGioLamThemFocusLost

    private void QLL_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_TimKiemActionPerformed
            try {
                    NhanVienDao dao = new NhanVienDao();
                    NhanVien nv = dao.findById(QLL_txtTimKiem.getText());
                    
                    if  ( nv != null ){
                            QLL_txtMaNhanVien.setText(nv.getMaNhanVien());
                            QLL_txtHoTenNV.setText(nv.getHoTen());
                            QLL_txtSDT.setText(nv.getSDT());
                            QLL_txtChucVu.setText(nv.getChucVu());
                             
//                        BangLuongDao BLDao = new BangLuongDao();
//                        BangLuong BL = BLDao.findByMaNhanVien(QLL_txtMaNhanVien.getText());
//                              if(BL != null){
//                    QLL_txtMaNhanVien.setText(BL.getMaNhanVien());
//                    QLL_txtHoTenNV.setText(BL.getHoTenNV());
//                    QLL_txtSoNgayNghi.setText(String.valueOf(BL.getSoNgayNghi()));
//                    QLL_txtGioLamThem.setText(String.valueOf(BL.getSoGioLamThem()));
//                    QLL_txtChucVu.setText(nv.getChucVu());
//                    QLL_txtSDT.setText(nv.getSDT());
//                  
//                   
//                     if(QLL_txtChucVu.getText().equals("Trưởng Phòng")){
//                                QLL_txtPhuCap.setText(String.valueOf((int)(BL.getTinhLuong()-
//                                 ((2600000 *2/26)* (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText())) +
//                                 (Integer.parseInt(QLL_txtGioLamThem.getText()) * 50000)))));
//                     }else if(QLL_txtChucVu.getText().equals("Nhân Viên")){
//                         QLL_txtPhuCap.setText(String.valueOf((int)(BL.getTinhLuong() -
//                                 ((2600000*1.5 /26)* (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText())) +
//                                 (Integer.parseInt(QLL_txtGioLamThem.getText()) * 25000)))));
//              
//                    }
//                    
//                   
//                    //Cắt Chuỗi và lấy giá trị của chuỗi 
//                    String[] splits = BL.getThang().split("/");
//                    QLL_cbb_Thang.setSelectedItem(splits[0]);
//                    QLL_cbb_Nam.setSelectedItem(splits[1]);
//
//                    
//                    QLL_lbl_TongLuong.setText(String.valueOf(BL.getTinhLuong()));
//                }
            
                      }else{
                            HienThiThongBao.ThongBao(parentform, "Không Tìm Thấy Mã Nhân Viên Theo Yêu Cầu", "Thông Báo");
                    }
                    
        } catch (Exception e) {
                    e.printStackTrace();
                    HienThiThongBao.ThongBaoLoi (parentform, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_QLL_btn_TimKiemActionPerformed

    private void QLL_btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_XoaActionPerformed
        
           try {
           // Kiểm tra dữ liệu đã được nhập chưa
                        if ( QLL_txtMaNhanVien.getText().equals(""))           {
                              HienThiThongBao.ThongBaoLoi(parentform, "Mã Nhân Viên Cần Phải Nhập", "Lỗi");
                          }
  
                        BangLuongDao BLdao = new BangLuongDao();
                        BangLuong bd = BLdao.findByMaNhanVien(QLL_txtMaNhanVien.getText());
           // Kiểm tra mã sinh viên trong csdl
                        if (bd == null){
                            HienThiThongBao.ThongBaoLoi(parentform, "Mã Nhân Viên Không Tồn Tại Trong Bảng Lương ", " Lỗi");
                            return;
                           
                        }
                        
            // Xác nhận lại yêu cầu cập nhật người dùng
                        if(HienThiThongBao.ThongBaoXacNhan (parentform,"Bạn Có Muốn Xóa Lương Của Nhân Viên Không" , "Hỏi") == JOptionPane.NO_OPTION){
                                return;
                        }
                        
                        if  ( BLdao.deleteByMaNhanVien(QLL_txtMaNhanVien.getText())){
                                HienThiThongBao.ThongBao (parentform, "Lương Nhân Viên Đã Được Xóa", "Thông Báo");
                                TaiDuLieuVaoBang(); 
                        }else{
                                HienThiThongBao.ThongBao (parentform, "Lương Nhân Viên Không Thể Xóa Được", "Thông Báo");
                        }

           } catch (Exception e) {          
            e.printStackTrace();
            HienThiThongBao.ThongBaoLoi(parentform, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_QLL_btn_XoaActionPerformed

    private void QLL_table_BangLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLL_table_BangLuongMouseClicked
  
           
   //     Lấy dữ liệu từ bẩng quản lí lương
        try {
            int row = QLL_table_BangLuong.getSelectedRow();
            
            if(row >= 0){
                String id = (String) QLL_table_BangLuong.getValueAt(row, 0);
                BangLuongDao dao = new BangLuongDao();
                BangLuong BL = dao.findByMaNhanVien(id);
              NhanVienDao nvdao = new NhanVienDao();
              NhanVien NV = (NhanVien) nvdao.findById(id);
                
                if(BL != null){
                    QLL_txtMaNhanVien.setText(BL.getMaNhanVien());
                    QLL_txtHoTenNV.setText(BL.getHoTenNV());
                    QLL_txtSoNgayNghi.setText(String.valueOf(BL.getSoNgayNghi()));
                    QLL_txtGioLamThem.setText(String.valueOf(BL.getSoGioLamThem()));
                    QLL_txtChucVu.setText(NV.getChucVu());
                    QLL_txtSDT.setText(NV.getSDT());
                  
                   
                     if(QLL_txtChucVu.getText().equals("Trưởng Phòng")){
                                QLL_txtPhuCap.setText(String.valueOf((int)(BL.getTinhLuong()-
                                 ((2600000 *2/26)* (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText())) +
                                 (Integer.parseInt(QLL_txtGioLamThem.getText()) * 50000)))));
                     }else if(QLL_txtChucVu.getText().equals("Nhân Viên")){
                         QLL_txtPhuCap.setText(String.valueOf((int)(BL.getTinhLuong() -
                                 ((2600000*1.5 /26)* (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText())) +
                                 (Integer.parseInt(QLL_txtGioLamThem.getText()) * 25000)))));
              
                    }
                    
                   
                    //Cắt Chuỗi và lấy giá trị của chuỗi 
                    String[] splits = BL.getThang().split("/");
                    QLL_cbb_Thang.setSelectedItem(splits[0]);
                    QLL_cbb_Nam.setSelectedItem(splits[1]);

                    
                    QLL_lbl_TongLuong.setText(String.valueOf(BL.getTinhLuong()));
                }
            }
        } catch (Exception e) {
             e.printStackTrace();
            HienThiThongBao.ThongBaoLoi(parentform, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_QLL_table_BangLuongMouseClicked



    private void QLL_btn_TinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLL_btn_TinhLuongActionPerformed

           // Kiểm tra dữ liệu đã được nhập?
            StringBuilder sb = new StringBuilder();
            KTra_DuLieu.validateEmpty(QLL_txtGioLamThem, sb, "Giờ Làm Thêm Chưa Được Nhập");           
            KTra_DuLieu.validateEmpty(QLL_txtSoNgayNghi, sb, " Số Giờ Nghỉ Của Nhân Viên Chưa Được Nhập");
             KTra_DuLieu.validateEmpty(QLL_txtPhuCap, sb, " Tiền Phụ Cấp Chưa Được Nhập");
        
         // Lương Cơ Bản
 if(QLL_txtChucVu.getText().equals("Trưởng Phòng")){
            LuongCoBan =2600000*2;
               TongLuong =(2600000*2)/26 * (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText())) 
                    + (Integer.parseInt(QLL_txtGioLamThem.getText()) * 50000) + Integer.parseInt(QLL_txtPhuCap.getText());
        }else if(QLL_txtChucVu.getText().equals("Nhân Viên")){
              LuongCoBan = (float) (2600000 * 1.5);
                    TongLuong =(float) ((2600000*1.5)/26 * (26 - Integer.parseInt(QLL_txtSoNgayNghi.getText()))
                            + (Integer.parseInt(QLL_txtGioLamThem.getText()) * 25000)+Integer.parseInt(QLL_txtPhuCap.getText()));
        }

//// Tông Lương
//        if(QLL_txtChucVu.getText().equals("Trưởng Phòng")){
//         
//        }else if(QLL_txtChucVu.getText().equals("Nhân Viên")){
//        
//        }
        
        QLL_lbl_TongLuong.setText(String.valueOf(TongLuong));
    }//GEN-LAST:event_QLL_btn_TinhLuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QLL_btn_CapNhat;
    private javax.swing.JButton QLL_btn_Luu;
    private javax.swing.JButton QLL_btn_NhapMoi;
    private javax.swing.JButton QLL_btn_TimKiem;
    private javax.swing.JButton QLL_btn_TinhLuong;
    private javax.swing.JButton QLL_btn_Xoa;
    private javax.swing.JComboBox<String> QLL_cbb_Nam;
    private javax.swing.JComboBox<String> QLL_cbb_Thang;
    private javax.swing.JLabel QLL_lbl_TongLuong;
    private javax.swing.JTable QLL_table_BangLuong;
    private javax.swing.JTextField QLL_txtChucVu;
    private javax.swing.JTextField QLL_txtGioLamThem;
    private javax.swing.JTextField QLL_txtHoTenNV;
    private javax.swing.JTextField QLL_txtMaNhanVien;
    private javax.swing.JTextField QLL_txtPhuCap;
    private javax.swing.JTextField QLL_txtSDT;
    private javax.swing.JTextField QLL_txtSoNgayNghi;
    private javax.swing.JTextField QLL_txtTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
